// toolbar配置
const items = [
    // "source",
    // "|",
    "print",
    "undo",
    "redo",
    "wordpaste",
    "|",
    // "fullscreen",
    // "/",
    "fontname",
    "formatblock",
    "fontsize",
    // "|",
    "forecolor",
    "hilitecolor",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "lineheight",
    "removeformat",
    "|",
    // "preview",
    // "template",
    // "code",
    // "cut",
    // "copy",
    // "paste",
    // "plainpaste",
    // "|",
    "justifyleft",
    "justifycenter",
    "justifyright",
    "justifyfull",
    "insertorderedlist",
    "insertunorderedlist",
    "indent",
    "outdent",
    "subscript",
    "superscript",
    // "clearhtml",
    "quickformat",
    // "selectall",
    "|",
    "image",
    // "multiimage",
    // "flash",
    // "media",
    // "insertfile",
    "table",
    // "hr",
    // "emoticons",
    // "baidumap",
    "pagebreak",
    // "anchor",
    // "link",
    // "unlink",
    // "|",
    // "about"
];

export default items;


